FROM golang:1.17-alpine3.15 AS builder
ENV GO111MODULE=on
WORKDIR /build
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o demo-api

###
FROM alpine:3.15 AS dist
RUN mkdir /app && \
    addgroup -S user && adduser -S user -G user \
    && chown -R user:user /app

USER user
COPY --from=builder --chown=user /build/demo-api /app/

WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["./demo-api"]
