version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=sns,sqs
#      - DEBUG=${DEBUG-true}
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${PWD}/localstack/localstack-init.sh:/docker-entrypoint-initaws.d/init.sh"
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "${PWD}/postgres:/docker-entrypoint-initdb.d/"
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - dev

  modulo-escolar:
    image: modulo-escolar:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dojo_modulo_escolar
      BACKEND_PORT: 8080
      LOCALSTACK_HOST: localstack
    depends_on:
      - localstack
      - postgres
    networks:
      - dev

  financial:
    image: financial:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dojo_modulo_financeiro
      BACKEND_PORT: 8080
      LOCALSTACK_HOST: localstack
    depends_on:
      - localstack
      - postgres
    networks:
      - dev

networks:
  dev:

volumes:
  pgdata:
